title: Pyjamask 
theme: jekyll-theme-minimal
description: Pyjamask is a cipher designed to provide very efficient software implementation with very high order side-channel countermeasures. Pyjamask has been submitted to the NIST call for algorithms for lightweight cryptography standardization process.
